#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static-pie"
export XSERVERCFLAGS_CFLAGS="-fPIE"
export XSERVERLIBS_LIBS="-lXdmcp -lXfont -lfreetype -lm -lharfbuzz -pthread -lXtst -lXi -lXext -lXfixes -lX11 -lpthread -lxcb -lXau -lfontenc -lpng16 -lz"

for p in *.patch; do
	patch -p1 < "$p"
done

./configure \
  --prefix=/usr \
  --with-fontdir=/usr/share/fonts \
  --disable-xdmcp \
  --disable-xdm-auth-1

make
make DESTDIR="$1" install

# not compatible
rm -rf    "$1/usr/bin/Xvesa"

#install minimum requirement for bitmap fonts
mkdir -p "$1/usr/share/fonts/misc"
cp ./*.pcf.gz fonts.alias fonts.dir "$1/usr/share/fonts/misc"
