#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static-pie"
export XSERVERCFLAGS_CFLAGS="-fPIE"
export XSERVERLIBS_LIBS="/lib/*.a -lz -lfreetype -lpng16"

./configure \
  --prefix=/ \
  --with-fontdir=/share/fonts \
  --disable-xdmcp \
  --disable-xdm-auth-1

make
make DESTDIR="$1" install

chmod u+s "$1/bin/Xfbdev"

# not compatible
rm -rf    "$1/bin/Xvesa"

#install minimum requirement for bitmap fonts
mkdir -p "$1/share/fonts/misc"
cp ./*.pcf.gz fonts.alias fonts.dir "$1/share/fonts/misc"
