#!/bin/sh -e

export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dtests=false \
    build

samu -C build
muon -C build install

# Fix pkgconf location
mkdir -p "$1/usr/lib"
mv -f "$1/usr/share/pkgconfig" "$1/usr/lib"
