#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

make \
    prefix=/ \
    CC="$CC -static $LDFLAGS $CFLAGS $CXXFLAGS" \
    -f unix/Makefile generic

make \
    prefix="$1/" \
    MANDIR="$1/share/man/man1" \
    -f unix/Makefile install
