#!/bin/sh -e

export CFLAGS="$CFLAGS -DNO_BZIP_SUPPORT"


for p in *.patch; do
    patch -p1 < "$p"
done

# The ZIPS variable is intentionally single quoted
# shellcheck disable=SC2016
make \
    prefix=/usr \
    CC="$CC -static $LDFLAGS $CFLAGS $CXXFLAGS" \
    ZIPS='zip$E' \
    -f unix/Makefile generic

# The ZIPS variable is intentionally single quoted
# shellcheck disable=SC2016
make \
    prefix="$1/usr" \
    MANDIR="$1/usr/share/man/man1" \
    ZIPS='zip$E' \
    -f unix/Makefile install

# We only build and install zip. Remove redundant manpages
for p in zipnote zipsplit zipcloak; do
	rm -rf "$1/usr/share/man/man1/$p.1"
done

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
