#!/bin/sh -e

export DESTDIR="$1"

# Disable building tests.
: > test/meson.build

muon setup \
	-Dprefix=/usr \
	-Dsysconfdir=/etc \
	-Dmandir=/usr/share/man \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	-Ddefault_library=shared \
	-Dx11=true \
	build

samu -C build
muon -C build install
