#!/bin/sh -e

export DESTDIR="$1"

# Disable building tests.
: > test/meson.build

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Dx11=true \
    build

samu -C build
samu -C build install
