#!/bin/sh -e

./configure \
    --prefix=/ \
    --disable-examples \
    --disable-python-bindings \
    --enable-lib-only

make
make DESTDIR="$1" install

# Compress manpages
find "$1/share/man" -type f | xargs gzip -n -9
