#!/bin/sh -e

./configure \
    --prefix=/ \
    --libexecdir=/bin \
    --localstatedir=/var \
    --disable-dbus \
    --disable-shared \
    --enable-static

make LDFLAGS="$LDFLAGS -static-pie" CFLAGS="$CFLAGS -fPIE"
make DESTDIR="$1" install

cp -f iwd_passphrase "$1/bin"

mkdir -p "$1/etc/rcsm/avail"
cp -f  eiwd.run "$1/etc/rcsm/avail/eiwd"

# Compress manpages
gzip -9 -n "$1/share/man/man8/iwd.8"
gzip -9 -n "$1/share/man/man7/iwd.debug.7"
gzip -9 -n "$1/share/man/man5/iwd.ap.5"
gzip -9 -n "$1/share/man/man5/iwd.network.5"
gzip -9 -n "$1/share/man/man5/iwd.config.5"
gzip -9 -n "$1/share/man/man1/iwmon.1"
