#!/bin/sh -e

export CXXFLAGS="$CXXFLAGS -static-libstdc++ -static-libgcc"

# Change the order for checking installed compilers as
# the ccache clang symlink might exist, but clang might not be installed.
sed 's/clang gcc cc/cc clang gcc/g' icu4c/source/configure > _
mv -f _ icu4c/source/configure
sed 's/clang++ g++ c++/c++ clang++ g++/g' icu4c/source/configure > _
mv -f _ icu4c/source/configure

# license installation seems to give us a symolic link loop, which breaks the install
sed '/LICENSE/d' icu4c/source/Makefile.in > _
mv -f _ icu4c/source/Makefile.in

sh icu4c/source/configure \
    --prefix=/usr \
    --sbindir=/usr/bin

make
make DESTDIR="$1" install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
