#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-docs.patch

cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_INSTALL_BINDIR=/usr/bin \
    -DCMAKE_INSTALL_INCLUDEDIR=/usr/bin \
    -DCMAKE_INSTALL_MANDIR=/usr/share/man \
    -DCMAKE_SHARED_LIBS=False \
    -DCMAKE_STATIC_LIBS=True \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_JPEG8=1

samu -C build
samu -C build install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
