#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-docs.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/ \
    -DCMAKE_INSTALL_LIBDIR=/lib \
    -DCMAKE_SHARED_LIBS=False \
    -DCMAKE_STATIC_LIBS=True \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_JPEG8=1

cmake --build   build
cmake --install build
