#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-docs.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/pkg \
    -DCMAKE_INSTALL_LIBDIR=/pkg/lib \
    -DCMAKE_INSTALL_BINDIR=/pkg/bin \
    -DCMAKE_INSTALL_INCLUDEDIR=/pkg/bin \
    -DCMAKE_INSTALL_MANDIR=/pkg/share \
    -DCMAKE_SHARED_LIBS=False \
    -DCMAKE_STATIC_LIBS=True \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_JPEG8=1

cmake --build   build
cmake --install build

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
