#!/bin/sh -e

# we only need the header and library, so dont build the bin
# shellcheck disable=SC2016
sed 's/jbig2dec\$(EXEEXT)//' Makefile.in > _
mv -f _ Makefile.in

./configure \
    --prefix=/usr \
    --disable-shared \
    --without-libpng

make
make DESTDIR="$1" install

# shellcheck disable=SC2115
rm -rf "$1/usr/share"
