#!/bin/sh -e

# Required by qt5 and possibly other software.
export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_COLUMN_METADATA"

./configure \
    --prefix=/pkg \
    --enable-threadsafe \
    --enable-dynamic-extensions \
    --enable-fts5 \
    --disable-shared \
    ac_cv_search_readline=no \
    CFLAGS="$CFLAGS -fPIE" \
    LDFLAGS="$LDFLAGS -static-pie"

make
make DESTDIR="$1" install
