#!/bin/sh -e

./configure \
    --prefix=/pkg \
    --without-xmlwf \
    --without-examples \
    --without-tests \
    --without-docbook

make
make DESTDIR="$1" install

# Remove documentation (Changelogs, etc).
rm -rf "${1:?}/pkg/share"
