#!/bin/sh -e

./configure \
    --prefix=/ \
    --without-xmlwf \
    --without-examples \
    --without-tests \
    --without-docbook \
    --disable-shared

make
make DESTDIR="$1" install

# Remove documentation (Changelogs, etc).
rm -rf "${1:?}/share"
