#!/bin/sh -e

# Disable stripping of binaries.
# This breaks Go.
:> nostrip

for p in *.patch; do
    patch -p1 < "$p"
done

export CC="${CC:-cc}"
export GOARCH=amd64
export GO_LDFLAGS="-w -s"

export GOROOT_BOOTSTRAP="/usr/lib/go1.17.13"
export GOROOT="$PWD"
export GOROOT_FINAL="/usr/lib/go"

(
    cd src
    ./make.bash -v
)

cd "$GOROOT"

mkdir -p "$1/usr/bin" "$1/usr/lib/go"

ln -s ../lib/go/bin/go    "$1/usr/bin"
ln -s ../lib/go/bin/gofmt "$1/usr/bin"

cp -pPR misc bin pkg src lib go.env "$1/usr/lib/go"

# Remove unneeded files.
rm -f  "$1/usr/share/go/doc/articles/wiki/get.bin"
rm -f  "$1/usr/lib/go/pkg/tool/"*/api
rm -rf "$1/usr/lib/go/pkg/bootstrap"
rm -rf "$1/usr/lib/go/pkg/obj"

# Remove tests.
for path in "$1/usr/lib/go/src" "$1/usr/lib/go/misc/cgo"
do
    find "$path" -type f -a -name \*_test.go -depth -exec rm {} +
    find "$path" -type f -a -name \*.bash    -depth -exec rm {} +
    find "$path" -type f -a -name \*.bat     -depth -exec rm {} +
    find "$path" -type f -a -name \*.rc      -depth -exec rm {} +
done

find . -type d -a -name testdata |
    while read -r dir; do
        rm -rf "$dir"
    done
