#!/bin/sh -e

export DESTDIR="$1"

# Set -Ddefault_library=both by default.
sed "s/\(value: \)'static'/\1'both'/" src/script/per_project_options.meson > _
mv -f _ src/script/per_project_options.meson

command -v muon > /dev/null || {
      ./bootstrap.sh build
    export PATH=$PWD/build:$PATH
    
}

muon setup \
      -Dprefix=/ \
      -Ddocs=disabled \
      -Dlibcurl=disabled \
      -Dlibpkgconf=disabled \
      -Dstatic=true \
      build

samu -C build
muon  -C build install
