#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-fix-incompatability-with-byacc.patch

muon setup \
	-Dprefix=/usr \
	-Dlibexecdir=/usr/lib \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddbghelp=disabled \
	-Dintrospection=disabled \
	-Dexamples=disabled \
	-Ddoc=disabled \
	-Dtests=disabled \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
