#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-fix-incompatability-with-byacc.patch

meson setup \
	-Dprefix=/usr \
	-Dlibexecdir=/usr/lib \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
	-Ddbghelp=disabled \
	-Dintrospection=disabled \
	-Dexamples=disabled \
	-Ddoc=disabled \
	-Dtests=disabled \
	build

samu -C build
samu -C build install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
