#!/bin/sh -e

./configure \
    --prefix=/ \
    --sysconfdir=/etc \
    --mandir=/share/man \
    --localstatedir=/var

make
make DESTDIR="$1" install

# Compress manpages
find "$1/share/man" -type f | xargs gzip -n -9
