#!/bin/sh -e

: > build-aux/missing

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --disable-nls \
    --disable-doc \
    --disable-tests

make
make DESTDIR="$1" install
