#!/bin/sh -e

./configure \
	PROG_LDADD=-all-static \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-tests

make
make DESTDIR="$1" install

# Certs is provided elsewhere
rm -rf "$1/etc/ssl/cert.pem"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

# Find and remove symlinks that are now broken
find "$1/usr/share/man" -type l -exec rm -r {} +