#!/bin/sh -e

./configure \
	PROG_LDADD=-all-static \
    --prefix=/pkg \
    --sysconfdir=/etc \
    --disable-tests

make
make DESTDIR="$1" install

# Certs is provided elsewhere
rm -rf "$1/etc/ssl"

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
