#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-fix-enum-types-for-muon.patch

: > po/meson.build

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddebug=false \
    -Djpeg=enabled \
    -Dpng=enabled \
    -Dtiff=disabled \
    -Dgtk_doc=false \
    -Ddocs=false \
    -Dman=false \
    -Dgio_sniffing=false \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    -Dgio_sniffing=false \
    -Dwrap_mode=nofallback \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Ddefault_library=both \
    build

samu -C build
muon -C build install
