#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-fix-enum-types-for-muon.patch

: > po/meson.build

muon setup \
	-Dprefix=/usr \
	-Dsysconfdir=/etc \
	-Dmandir=/usr/share/man \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Djpeg=enabled \
	-Dpng=enabled \
	-Dtiff=disabled \
	-Dgtk_doc=false \
	-Dman=false \
	-Dgio_sniffing=false \
	-Dtests=false \
	-Dinstalled_tests=false \
	-Dbuiltin_loaders=all \
	-Dwrap_mode=nofallback \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install

rm -rf "$1/usr/share/thumbnailers"
