#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-remove-arch4random_buf-call.-it-does-not-exist.patch

if kiss l cmake; then
    cmake -G Ninja -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_USE_SYSTEM_CURL=False \
        -DCMAKE_USE_SYSTEM_EXPAT=True \
        -DCMAKE_USE_SYSTEM_ZLIB=True \
        -DCMAKE_USE_SYSTEM_BZIP2=False \
        -DCMAKE_USE_SYSTEM_NGHTTP2=False \
        -DBUILD_CursesDialog=OFF \
        -DBUILD_TESTING=OFF

    cmake --build   build
    cmake --install build

else
    ./configure \
        --prefix=/usr \
        --no-system-curl \
        --system-expat \
        --system-zlib \
        --no-system-bzip2 \
        --generator=Ninja \
        --parallel="$(grep -scF 'core id' /proc/cpuinfo)" -- \
        -DBUILD_CursesDialog=OFF

    samu
    samu install
fi

rm -rf \
    "$1/usr/doc" \
    "$1/usr/share/cmake"*/Help \
    "$1/usr/share/bash-completion"
