#!/bin/sh -e

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

patch -p1 < 0001-remove-gio-querymodule-post-install.patch

# Don't build tests that fail due to `gnutls` not being built with `p11-kit`.
sed "/subdir('tests')/d" tls/meson.build > _
mv -f _ tls/meson.build

: > po/meson.build

muon setup \
	-Dprefix=/usr \
	-Dsysconfdir=/etc \
	-Dlocalstatedir=/var \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Dlibproxy=disabled \
	-Dopenssl=disabled \
	-Dgnutls=enabled \
	-Dgnome_proxy=disabled \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install
