#!/bin/sh -e

export DESTDIR="$1"

TMPDIR="$1/tmp"

./configure \
    --prefix=/ \
    --sysconfdir=/etc \
    --mandir=/share/man \
    --localstatedir=/var \
    XAUTH_CFLAGS="-static"

make LIBS="/lib/*.a /lib/libXau.a /lib/libxcb.a"
make install

# Some X11 packages install to /share.
! [ -d "$1/share/pkgconfig" ] || {
    mkdir -p "$1/lib"
    mv -f "$1/share/pkgconfig" "$1/lib"
}

# We need to keep this around.
! [ -d "$1/share/aclocal" ] || {
    mkdir -p "$TMPDIR"
    mv -f "$1/share/aclocal" "$TMPDIR"
}

# Restore kept directories.
! [ -d "$TMPDIR" ] || {
    mv -f "$TMPDIR/"* "$1/share"
    rm -rf "$TMPDIR"
}
