#!/bin/sh -e

./configure \
    --prefix=/ \
    --disable-tiff \
    --enable-libwebpmux \
    --enable-libwebpdemux \
    --enable-libwebpdecoder

make
make DESTDIR="$1" install

# Compress manpages
find "$1/share/man" -type f | xargs gzip -n -9
