#!/bin/sh -e

./configure \
    --prefix=/pkg \
    --without-python \
    --without-debugger \
    --without-debug \
    --without-crypto

make
make DESTDIR="$1" install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
