#!/bin/sh -e

export DESTDIR="$1"

muon setup \
	-Dprefix=/usr \
	-Dintel=disabled \
	-Dnouveau=disabled \
	-Damdgpu=enabled \
	-Dradeon=enabled \
	-Dvalgrind=disabled \
	-Ddefault_library=both \
	-Dman-pages=disabled \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	build

samu -C build
muon -C build install
