#!/bin/sh -e

export CFLAGS="$CFLAGS -std=c99 -pedantic -fPIE"
export LDFLAGS="$LDFLAGS -static-pie"

make libxxhash.a xxhsum
make PREFIX=/usr DESTDIR="$1" install_libxxhash.a \
	install_libxxhash.includes \
	install_libxxhash.pc \
	install_xxhsum \
	install_man
