#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-shared \
    --enable-static \
    --disable-rpath

make
make DESTDIR="$1" install

# Compress manpages
find "$1/usr/share/man" -type f | xargs gzip -n -9
