#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr

make
make install

# Remove HTML documentation.
rm -rf "$1/usr/share/doc"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
