#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static-pie"
export CFLAGS="$CFLAGS -fPIE"

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

rm -rf \
	"$1/usr/share/doc" \
	"$1/usr/share/info"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
