#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/pkg

make
make install

# Remove HTML documentation.
rm -rf "$1/pkg/share/doc"

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
