#!/bin/sh -e

./configure \
    --prefix=/pkg \
    --disable-nls \
    --with-nettle-mini \
    --with-included-libtasn1 \
    --with-included-unistring \
    --enable-static \
    --without-p11-kit

make
make DESTDIR="$1" install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
