#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

# uncomment everything here to build it statically
sed 's/--libs fontconfig/--libs --static fontconfig/' config.mk > _
mv -f _ config.mk 
sed 's/--libs freetype2/--libs --static freetype2/' config.mk > _
mv -f _ config.mk

make \
	LDFLAGS="$LDFLAGS -static-pie -lX11 -lXft \
	-lxcb -lX11-xcb -lXrender -lXau"
make PREFIX=/usr DESTDIR="$1" install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
