#!/bin/sh -e

export DESTDIR="$1"

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Ddoc=disabled \
	-Dtests=disabled \
	-Db_colorout=never \
	-Ddefault_library=both \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	output

samu -C output
muon -C output install
