#!/bin/sh -e

patch -p1 < top-bar.patch

go build -a -ldflags="-w -s -extldflags '-static'" \
    -trimpath \
    -modcacherw \
    ./cmd/senpai

scdoc < doc/senpai.1.scd > senpai.1
scdoc < doc/senpai.5.scd > senpai.5

mkdir -p "$1/usr/bin" "$1/usr/share/man/man1" "$1/usr/share/man/man5"

cp senpai "$1/usr/bin/"
cp senpai.1 "$1/usr/share/man/man1/"
cp senpai.5 "$1/usr/share/man/man5/"
