#!/bin/sh -e

patch -p1 < 0001-set-bar-to-be-on-top-of-the-window-instead-of-bottom.patch

go build -a -ldflags="-w -s -extldflags '-static'" \
    -trimpath \
    -modcacherw \
    ./cmd/senpai

if command -v scdoc; then
	scdoc < doc/senpai.1.scd > senpai.1
	scdoc < doc/senpai.5.scd > senpai.5
	
	mkdir -p \
		"$1/usr/share/man/man1" \
		"$1/usr/share/man/man5"

	cp senpai.1 "$1/usr/share/man/man1/"
	cp senpai.5 "$1/usr/share/man/man5/"

	# Compress manpages
	find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
fi

mkdir -p "$1/usr/bin"

cp senpai "$1/usr/bin/"
