#!/bin/sh -e

export CFLAGS="$CFLAGS -fasynchronous-unwind-tables"
export LDFLAGS="$LDFLAGS -static-libgcc"

patch -p1 < 0001-fix-check-for-toolchain-generateing-unwind-tables.patch

make amalg   PREFIX=/usr
make install PREFIX=/usr DESTDIR="$1" INSTALL_TNAME=luajit

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
