#!/bin/sh -e

export PATH=/usr/bin:$PATH

# Swap to shell script instead of perl script
# for conversion of rules files. See files/xml2lst.
sed 's/xml2lst\.pl/xml2lst/' rules/meson.build > _
mv -f _ rules/meson.build

# Remove po/ dir.
sed "/subdir('po')/d" meson.build > _
mv -f _ meson.build

export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Dnls=false \
    build

samu -C build
muon -C build install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

# fix manpage symlink
ln -sf xkeyboard-config-2.7.gz "$1/usr/share/man/man7/xkeyboard-config.7"
