#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

# force use webkit 4.1
sed 's/4.0/4.1/g' config.mk > _
mv -f _ config.mk

# Set a more sane default window size
sed 's/800, 600/800, 900/' config.def.h > _
mv -f _ config.def.h

make
make DESTDIR="$1" PREFIX=/usr install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
