#!/bin/sh -e

export DESTDIR="$1"
export XAU_CFLAGS=-I/pkg/include
export XAU_LIBS=-L/pkg/lib

TMPDIR="$1/tmp"

./configure \
    --prefix=/pkg \
    --sysconfdir=/etc \
    --mandir=/pkg/share/man \
    --localstatedir=/var \
    --without-xmlto \
    --disable-specs

make
make install

# Some X11 packages install to /pkg/share.
! [ -d "$1/pkg/share/pkgconfig" ] || {
    mkdir -p "$1/pkg/lib"
    mv -f "$1/pkg/share/pkgconfig" "$1/pkg/lib"
}

# We need to keep this around.
! [ -d "$1/pkg/share/aclocal" ] || {
    mkdir -p "$TMPDIR"
    mv -f "$1/pkg/share/aclocal" "$TMPDIR"
}

# Restore kept directories.
! [ -d "$TMPDIR" ] || {
    mv -f "$TMPDIR/"* "$1/pkg/share"
    rm -rf "$TMPDIR"
}

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
