#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static"
export CFLAGS="$CFLAGS \
	-D_FILE_OFFSET_BITS=64 \
	-DWILD_STOP_AT_DIR \
	-DLARGE_FILE_SUPPORT \
	-DUNICODE_SUPPORT \
	-DUNICODE_WCHAR \
	-DUTF8_MAYBE_NATIVE \
	-DNO_LCHMOD \
	-LDDATE_FORMAT=DF_YMD \
	-DNATIVE"

make \
    LF2="$LDFLAGS" CF="$CFLAGS $CPPFLAGS -I." \
    prefix="$1/usr" \
    -f unix/Makefile unzips

make \
    prefix="$1/usr"  \
    MANDIR="$1/usr/share/man/man1" \
    -f unix/Makefile install

# Compress manpages
find "$1/usr/share/man" -type f | xargs gzip -n -9
