#!/bin/sh -e

while read -r p; do
    patch -p1 < "$p"
done < series

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static -L/src/oakiss/out/usr/bzip2"
export CFLAGS="$CFLAGS \
	-I/src/oakiss/usr/bzip2/src \
	-D_FILE_OFFSET_BITS=64 \
	-DWILD_STOP_AT_DIR \
	-DLARGE_FILE_SUPPORT \
	-DUNICODE_SUPPORT \
	-DUNICODE_WCHAR \
	-DUTF8_MAYBE_NATIVE \
	-DNO_LCHMOD \
	-LDDATE_FORMAT=DF_YMD \
	-DUSE_BZIP2 \
	-DNATIVE"

make \
    D_USE_BZ2=-DUSE_BZIP2 L_BZ2=-lbz2 \
    LF2="$LDFLAGS" CF="$CFLAGS $CPPFLAGS -I." \
    prefix="$1/" \
    -f unix/Makefile unzips

make \
    prefix="$1/"  \
    MANDIR=/usr/share/man/man1 \
    -f unix/Makefile install

# Compress manpages
find "$1/usr/share/man" -type f | xargs gzip -n -9
