#!/bin/sh -e

export DESTDIR="$1"

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
	-Ddoc=disabled \
	-Dtests=disabled \
	build

samu -C build
samu -C build install
