#!/bin/sh -e

export DESTDIR="$1"

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
	-Ddoc=disabled \
	-Dtests=disabled \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install
