#!/bin/sh -e

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

: > fuzzing/meson.build
: > subprojects/gvdb.wrap

muon setup \
	-Dprefix=/usr \
	-Dlibexecdir=/usr/lib \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Dlibmount=disabled \
	-Dinstalled_tests=false \
	-Dman-pages=disabled \
	-Dtests=false \
	-Dlibelf=disabled \
	-Dnls=disabled \
	-Dsysprof=disabled \
	-Dglib_debug=disabled \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install

rm -rf "$1/usr/bin/gdbus"
