#!/bin/sh -e

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddoc=disabled \
	-Dtests=disabled \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install
