#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

# Remove util-linux dependency among other things.
cat >> Modules/Setup <<EOF
*disabled*
_uuid nis ossaudiodev
EOF

# Reported 20-27% performance improvements.
# See: "PythonNoSemanticInterpositionSpeedup"
export CFLAGS="$CFLAGS -fno-semantic-interposition"
export LDFLAGS="$LDFLAGS -fno-semantic-interposition"

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-shared \
    --with-system-ffi \
    --with-system-expat \
    --with-ensurepip=yes \
    --without-pymalloc \
    --disable-ipv6 \
    --with-builtin-hashlib-hashes="sha3,blake2,sha1,sha512,sha256,md5" \
    --with-ssl-default-suites="TLSv1.3:TLSv1.2+AEAD+ECDHE:TLSv1.2+AEAD+DHE" \
    ax_cv_c_float_words_bigendian=no

make EXTRA_CFLAGS="$CFLAGS -DTHREAD_STACK_SIZE=0x100000"
make DESTDIR="$1" install

ln -s python3 "$1/usr/bin/python"
ln -s pip3    "$1/usr/bin/pip"

# Let's make some kind of effort to reduce the overall
# size of Python by removing a bunch of rarely used and
# otherwise useless components.
#
# This can't be done via ./configure as the build system
# doesn't give you this much control over the process.
{
    cd "$1/usr/lib/python"*
    rm -rf test ./*/test ./*/tests
    rm -rf pydoc* idlelib turtle* config-*

    cd "$1/usr/bin"
    rm -f pydoc* idle*
}

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

# fix broken symlink
ln -sf python3.11.1.gz "$1/usr/share/man/man1/python3.1"

# A lot of python scripts use #!/usr/bin/env python
ln -sf ../../bin/env "$1/usr/bin/env"
