#!/bin/sh -e

patch -p1 < 0001-util-remove-malloc-stats.patch

export DESTDIR="$1"

meson setup \
	-Dprefix=/usr \
	-Dtee=enabled \
	-Dxcb=enabled \
	-Dxlib=enabled \
	-Dxlib-xcb=enabled \
	-Dtests=disabled \
	build

samu -C build
samu -C build install
