#!/bin/sh -e

patch -p1 < 0001-util-remove-malloc-stats.patch

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Dtee=enabled \
	-Dxcb=enabled \
	-Dxlib=enabled \
	-Dxlib-xcb=enabled \
	-Dtests=disabled \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install
