#!/bin/sh -e

patch -p1 < 0001-util-remove-malloc-stats.patch

export DESTDIR="$1"

muon setup \
	-Dprefix=/usr \
	-Dtee=enabled \
	-Dxcb=enabled \
	-Dxlib=enabled \
	-Dxlib-xcb=enabled \
	-Dtests=disabled \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	-Ddefault_library=both \
	build

samu -C build
muon -C build install
