#!/bin/sh -e

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

for p in *.patch; do
	patch -p1 < "$p"
done

# Disable download of missing (optional) dependencies
# during the build. This cannot be turned off otherwise.
rm -rf subprojects

: > tests/meson.build
: > examples/meson.build
: > docs/meson.build

muon setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Dgtk_doc=false \
	-Dintrospection=disabled \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install
