#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-remove-fribidi-dependency.patch

# Disable download of missing (optional) dependencies
# during the build. This cannot be turned off otherwise.
rm -rf subprojects

: > tests/meson.build
: > examples/meson.build
: > docs/meson.build

meson setup \
    -Dprefix=/usr \
    -Dlibdir=/usr/lib \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
    -Dgtk_doc=false \
    -Dintrospection=disabled \
    build

samu -C build
samu -C build install
