#!/bin/sh -e

export DESTDIR="$1"

for p in *.patch; do
	patch -p1 < "$p"
done

# Disable download of missing (optional) dependencies
# during the build. This cannot be turned off otherwise.
rm -rf subprojects

: > tests/meson.build
: > examples/meson.build
: > docs/meson.build

muon setup \
    -Dprefix=/usr \
    -Dlibdir=/usr/lib \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Db_colorout=never \
    -Dintrospection=disabled \
    -Dlibthai=disabled \
    -Dxft=disabled \
    -Ddocumentation=false \
    -Dbuild-testsuite=false \
    -Dbuild-examples=false \
    -Ddefault_library=both \
    build

samu -C build
muon -C build install
