#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-remove-fribidi-dependency.patch

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Dfontconfig=enabled \
	-Ddefault_library=both \
	-Dpkg_config_path=/usr/lib/pkgconfig \
	build

samu -C build
muon -C build install
