#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc/imlib2 \
	--x-libraries-=/usr/lib \
	--x-includes=/usr/include  \
    --enable-visibility-hiding

make
make install
