#!/bin/sh -e

export LDFLAGS="$LDFLAGS  --static"

# Use lib not lib64 by default.
sed '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64 > _
mv -f _ gcc/gcc/config/i386/t-linux64
sed 's/lib64/lib/' gcc/gcc/config/i386/linux64.h > _
mv -f _ gcc/gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

# Grab the system's GCC version.
gcc_version=$(gcc -dumpversion) || gcc_version=null

# Skip the bootstrap process if we are able.
case $2 in "$gcc_version"*)
    printf '%s\n' "Minor version difference, disabling bootstrap."
    bootstrap=--disable-bootstrap
esac

../gcc/configure \
    libat_cv_have_ifunc=no \
    --prefix=/ \
    --libexecdir=/lib \
    --mandir=/share/man \
    --infodir=/share/info \
    --disable-multilib \
    --disable-symvers \
    --disable-libmpx \
    --disable-libmudflap \
    --disable-libsanitizer \
    --disable-werror \
    --disable-fixed-point \
    --disable-libstdcxx-pch \
    --disable-nls \
    --enable-checking=release \
    --enable-__cxa_atexit \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-initfini-array \
    --enable-languages=c,c++ \
    --without-included-gettext \
    --with-zstd=no \
    --with-system-zlib \
    --build=x86_64-linux-musl \
    --disable-lto \
    "${bootstrap:---enable-bootstrap}"

make 
make DESTDIR="$1" install 

# Save 35MB.
find "$1" -name libgtkpeer.a  -exec rm -f {} +
find "$1" -name libgjsmalsa.a -exec rm -f {} +
find "$1" -name libgij.a      -exec rm -f {} +

ln -sf gcc "$1/bin/cc"
ln -sf x86_64-linux-musl-gcc "$1/bin/x86_64-linux-musl-cc"
ln -sf x86_64-linux-musl-gcc-ar "$1/bin/x86_64-linux-musl-ar"
ln -sf x86_64-linux-musl-gcc-ranlib "$1/bin/x86_64-linux-musl-ranlib"
cp -f ../c99 "$1/bin"
cp -f ../c11 "$1/bin"

# Compress manpages
gzip -9 -n "$1/share/man/man*/*"
