#!/bin/sh -e

patch -p1 < 0001-Don-t-use-C23-constexpr-keyword.patch

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" prefix=/usr install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

# Remove broken symlinks
rm -rf "$1/usr/share/man/man1/unifdefall.1"
