#!/bin/sh -e 

make \
	CFLAGS="$CFLAGS -I/usr/include" \
	LDFLAGS="$LDFLAGS -static -L/usr/lib -lxcb -lxcb-shm -lxcb-util -lxcb-image -lxcb-render-util -lxcb-render -lxcb-cursor -lXau /usr/lib/*.a"
make \
	MANPREFIX=/usr/share/man \
	PREFIX=/usr \
	DESTDIR="$1" \
	install

cd opt

make LDFLAGS="$LDFLAGS -static -lxcb -lxcb-util -lXau"
make \
	MANPREFIX=/usr/share/man \
	PREFIX=/usr \
	DESTDIR="$1" \
	install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
