#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-remove-the-need-for-vulkan-headers.patch

mk() (
	muon setup \
	    -Dprefix=/usr \
	    -Dbuildtype=release \
	    -Dvulkan=disabled \
	    -Ddemos=false \
	    -Dopengl=disabled \
	    "$@" \
	    build
	
	samu -C build
	muon -C build install
)

mk -Ddefault_library=static
mk -Ddefault_library=shared
