#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-remove-the-need-for-vulkan-headers.patch

muon setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dvulkan=disabled \
    -Ddemos=false \
    -Dopengl=disabled \
    -Dxxhash=disabled \
    -Ddefault_library=shared \
    build

samu -C build
muon -C build install
