#!/bin/sh -e

make -C lib libzstd.a
make -C lib PREFIX=/usr DESTDIR="$1" install-static
make -C lib PREFIX=/usr DESTDIR="$1" install-includes
make -C lib PREFIX=/usr DESTDIR="$1" install-pc

make -C programs \
	HAVE_LZMA=0 \
    HAVE_ZLIB=0 \
    HAVE_LZ4=0 \
	LDFLAGS="$LDFLAGS -static"

make -C programs PREFIX=/usr DESTDIR="$1" install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

# Fix symbolic links
ln -sf zstd.1.gz "$1/usr/share/man/man1/zstdcat.1"
ln -sf zstd.1.gz "$1/usr/share/man/man1/unzstd.1"
