#!/bin/sh -e

patch -p1 < drop-shared-libs.patch

sed 's/^FLAGS.*=/FLAGS = -static /' programs/Makefile > _
mv -f _ programs/Makefile

make \
    HAVE_LZMA=0 \
    HAVE_ZLIB=0 \
    HAVE_LZ4=0

make PREFIX=/usr DESTDIR="$1" install
