#!/bin/sh -e

make -C lib libzstd.a
make -C lib PREFIX=/usr DESTDIR="$1" install-static
make -C lib PREFIX=/usr DESTDIR="$1" install-includes
make -C lib PREFIX=/usr DESTDIR="$1" install-pc

make -C programs \
	HAVE_LZMA=0 \
    HAVE_ZLIB=0 \
    HAVE_LZ4=0 \
	LDFLAGS="$LDFLAGS -static"

make -C programs PREFIX=/usr DESTDIR="$1" install
