#!/bin/sh -e

./configure \
    --prefix=/ \
    --with-threads \
    --with-history \
    --without-python \
    --without-icu

make
make DESTDIR="$1" install

# Compress manpages
find "$1/share/man" -type f | xargs gzip -n -9
