#!/bin/sh -e

export GOPATH="$PWD/go"
export GO111MODULE=on

CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"'\
    -modcacherw \
    -trimpath \
    ./cmd/gh

install -Dm755 gh "$1/usr/bin/gh"
