#!/bin/sh -e

export DESTDIR="$1"

build_freetype() (
    cd freetype

    muon setup \
        -Dprefix=/usr \
        -Ddefault_library=both \
		-Dbuildtype=release \
		-Db_colorout=never \
        -Dbzip2=disabled \
        -Dzlib=disabled \
        "$@" \
        build

    samu -C build
    muon -C build install
)

build_harfbuzz() (
    cd harfbuzz

# harfbuzz-icu is basically harfbuzz with icu and glib enabled.
# this avoids a new package for stuff that can already be enabled here, which
# makes much more sense imo. glib remains disabled untill I get to test this
# further.
kiss list icu  >/dev/null 2>&1 || icu_enabled=disabled

    muon setup \
        -Dprefix=/usr \
        -Dpkg_config_path="$DESTDIR/usr/lib/pkgconfig:/usr/lib/pkgconfig" \
		-Dbuildtype=release \
		-Db_colorout=never \
        -Ddefault_library=both \
        -Dglib=disabled \
        -Dfreetype=enabled \
        -Dgobject=disabled \
        -Dcairo=disabled \
        -Dbenchmark=disabled \
        -Dicu="${icu_enabled:-enabled}" \
        -Dtests=disabled \
        -Dintrospection=disabled \
        build

    samu -C build
    muon -C build install
)

# Point Freetype to the Harfbuzz files.
export CPPFLAGS="$CPPFLAGS -I$DESTDIR/usr/include/harfbuzz"
export LDFLAGS="$LDFLAGS -L$DESTDIR/usr/lib "
export PKG_CONFIG_PATH="$DESTDIR/usr/lib/pkgconfig"

# Point Harfbuzz to the Freetype files.
export CPPFLAGS="$CPPFLAGS -I$DESTDIR/usr/include/freetype2"

build_freetype -Dharfbuzz=disabled
build_harfbuzz
build_freetype -Dharfbuzz=enabled
