#!/bin/sh -e

# Disable stripping of binaries.
# This breaks Go.
:> nostrip

patch -p1 < posix-build.patch

export CC="${CC:-cc}"
export GOARCH=amd64
export GO_LDFLAGS="-w -s"

mk() (
    export GOROOT="$1"
    export GOROOT_FINAL="$2"

    cd "$GOROOT"

    (
        cd src
        ./make.bash
    )

    mkdir -p "$GOROOT_FINAL"
    cp -pPR bin pkg src "$GOROOT_FINAL"
)

mk "$PWD/go1.4-bootstrap" "$PWD/lib/go1.4-bootstrap"

GOROOT_BOOTSTRAP="$PWD/lib/go1.4-bootstrap" \
    mk "$PWD/go1.17.13" "$PWD/lib/go1.17.13"

GOROOT_BOOTSTRAP="$PWD/lib/go1.17.13" \
    mk "$PWD/go$2" "$1/usr/lib/go$2"
