#!/bin/sh -e

export DESTDIR="$1"

# Fix issues with musl and firefox.
# https://bugs.freedesktop.org/show_bug.cgi?id=35268
# https://github.com/mesa3d/mesa/commit/9f37c9903b87f86a533bfaffa72f0ecb285b02b2
# https://gitlab.freedesktop.org/mesa/mesa/-/issues/966
sed "/pre_args += '-DUSE_ELF_TLS'/d" meson.build > _
mv -f _ meson.build

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
! kiss list libglvnd >/dev/null 2>&1 || glvnd_enabled=true

meson setup \
    -Dprefix=/ \
    -Dsysconfdir=/etc \
    -Dmandir=/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=x11 \
    -Dglx=auto \
    -Dgallium-drivers=swrast \
    -Degl=enabled \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dvulkan-drivers='' \
    -Dglvnd="${glvnd_enabled:-false}" \
    -Db_colorout=never \
    output

samu -C output
samu -C output install
