#!/bin/sh -e

export LIBS="-L/pkg/lib"
export CFLAGS="$CFLAGS -I/pkg/include"

./configure \
    --prefix=/pkg \
    --with-fontrootdir=/pkg/share/fonts/X11 \
    --disable-shared

make
make DESTDIR="$1" install
