#!/bin/sh -e

export PKG_CONFIG_PATH=/usr/lib/pkgconfig

make PREFIX=/usr USE_LUAJIT=1
make DESTDIR="$1" PREFIX=/usr install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

rm -rf \
	"$1/usr/share/pixmaps" \
	"$1/usr/share/applications" \
	"$1/usr/share/luakit/doc" \
	"$1/usr/share/luakit/resources"