#!/bin/sh -e

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

# byacc is only installed as yacc
sed 's/byacc/yacc/g' meson.build > _
mv -f _ meson.build

muon setup \
	-Dprefix=/usr \
	-Dlibexecdir=/usr/lib \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddefault_library=both \
	-Denable-docs=false \
	-Denable-wayland=true \
	-Denable-xkbregistry=false \
	build

samu -C build
muon -C build install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
