#!/bin/sh -e

export DESTDIR="$1"

# byacc is only installed as yacc
sed 's/byacc/yacc/g' meson.build > _
mv -f _ meson.build

meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Ddefault_library=static \
    -Denable-docs=false \
    -Denable-wayland=false \
    -Denable-xkbregistry=false \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    build

samu -C build
samu -C build install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
