#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/pkg \
    -Dlibexecdir=/pkg/lib \
    -Ddefault_library=static \
    -Denable-docs=false \
    -Denable-wayland=false \
    -Denable-xkbregistry=false \
    -Dpkg_config_path=/pkg/lib/pkgconfig \
    output

samu -C output
samu -C output install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
