#!/bin/sh -e

export LIBRARY_DIR=/usr/lib
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

patch -p1 < 0001-add-configure-check-for-Wno-error-incompatible-point.patch

./configure \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --prefix=/usr \
    --disable-debug \
    --disable-libxml2 \
    --disable-libtls \
    --enable-static \
    --enable-gpl \
    --enable-libdrm \
    --enable-libopus \
    --disable-sndio \
    --enable-alsa \
    --enable-shared \
    --enable-version3 \
    --x86asmexe=nasm

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/ffmpeg/examples"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
