#!/bin/sh -e

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

muon setup \
    -Dprefix=/usr \
    -Ddefault_library=both \
    -Dtests=false \
    -Ddocumentation=false \
    -Ddtd_validation=false \
    build

samu -C build
muon -C build install
