#!/bin/sh -e

# LDFLAGS isnt specified, but LIBS is.
make LIBS="$LIBS -static"
make \
	DESTDIR="$1" \
    PREFIX=/ \
    MANDIR=/share/man/man1 \
    install

# Compress manpages
find "$1/share/man" -type f | xargs gzip -n -9
