#!/bin/sh -e

python setup.py build
python setup.py install \
    --root="$1" \
    --optimize=1 \
    --skip-build

rm -rf "$1/usr/share/polkit-1"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
