#!/bin/sh -e

python packaging/create_zipapp.py \
	--outfile meson \
	--compress

chmod 755 meson
chmod 655 man/meson.1

mkdir -p \
	"$1/usr/bin" \
	"$1/usr/share/man/man1"

cp -f meson "$1/usr/bin"
cp -f man/meson.1 "$1/usr/share/man/man1"

# Compress manpages
find "$1/usr/share/man" -type f | xargs gzip -n -9
