#!/bin/sh -e

export DESTDIR="$1"

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
	-Dgtk=disabled \
	-Ddefault_library=both \
	build

samu -C build
muon -C build install
