#!/bin/sh -e

# Missing includes...
sed '/^#ifdef USE_JENT/a #include <fcntl.h>\n#include <limits.h>' \
    random/rndjent.c > _
mv -f _ random/rndjent.c

./configure \
    --prefix=/pkg \
    --sysconfdir=/etc \
    --mandir=/pkg/share/man \
    --localstatedir=/var

make
make DESTDIR="$1" install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
