#!/bin/sh -e

export DESTDIR="$1"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

# muon seems to make the check fail, and files seems to no be generated before
# check is ran. prompty making the build fail because pc files is missing.
patch -p1 < 0001-disable-check-for-pc-files.patch

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Dgl=disabled \
	-Dtests=disabled \
	-Dtremor=disabled \
	-Dexamples=disabled \
	-Dcdparanoia=disabled \
	-Dintrospection=disabled \
	-Dnls=disabled \
	-Ddoc=disabled \
	-Dalsa=enabled \
	-Ddefault_library=shared \
	build

samu -C build
muon -C build install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
