#!/bin/sh -e

./configure \
    --prefix=/pkg \
    --disable-exec-static-tramp \
    --enable-static

make
make DESTDIR="$1" install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
