#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-exec-static-tramp \
    --enable-static

make
make DESTDIR="$1" install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

rm -rf "$1/usr/share/info"
