#!/bin/sh -e

patch -p1 < configure-Pass-LDFLAGS-to-link-tests.patch

export CFLAGS="$CFLAGS -fPIC"

./configure \
    --prefix=/

make
make DESTDIR="$1" install

# Compress manpages
find "$1/share/man" -type f | xargs gzip -n -9
