#!/bin/sh -e

# fix sx for tinyx
sed -e 's/-keeptty//' \
	-e 's/exec Xorg/exec Xfbdev/' \
	sx > _
mv -f _ sx

mkdir -p \
	"$1/pkg/bin" \
	"$1/pkg/share/man/man1"

chmod 755 sx
chmod 655 sx.1

cp -f sx "$1/pkg/bin"
cp -f sx.1 "$1/pkg/share/man/man1"
