#!/bin/sh -e

# fix sx for tinyx
sed -e 's/-keeptty//' \
	-e 's/exec Xorg/exec Xfbdev/' \
	sx > _
mv -f _ sx

mkdir -p \
	"$1/usr/bin" \
	"$1/usr/share/man/man1"

chmod 755 sx
chmod 655 sx.1

cp -f sx "$1/usr/bin"
cp -f sx.1 "$1/usr/share/man/man1"

# Compress manpages
find "$1/usr/share/man" -type f | xargs gzip -n -9
