#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static"

cmake -G Ninja -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBEXECDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DREDIS_STORAGE_BACKEND=OFF \
    -DENABLE_TESTING=OFF \
    -DZSTD_LIBRARY=/src/oakiss/out/pkg/zstd/libzstd.a \
    -DZSTD_INCLUDE_DIR=/src/oakiss/out/pkg/zstd/include \
    -DZSTD_FROM_INTERNET=OFF \
    -DXXHASH_INCLUDE_DIR=/include \
    -DXXHASH_LIBRARY=/lib/libxxhash.a \
    -Wno-dev

samu -C build
samu -C build install

mkdir -p "$1/usr/lib/ccache/bin"
host=$(cc -dumpmachine)

for link in \
    cc  "$host-cc"  \
    gcc "$host-gcc" \
    g++ "$host-g++" \
    cpp "$host-cpp" \
    c++ "$host-c++"
do
    ln -sf /usr/bin/ccache "$1/usr/lib/ccache/bin/$link"
done
