#!/bin/sh -e

# vendor libwm, as its not needed elsewhere at all
(
cd libwm

make \
	CFLAGS="$CFLAGS -I/usr/include"
)

patch -p1 < 0001-exclude-ewmh-all-together.patch

make CFLAGS="$CFLAGS -I./libwm" \
	LDFLAGS="$LDFLAGS -L./libwm -lwm -lxcb -lXau -lxcb-cursor -lxcb-render -lxcb-render-util -lxcb-image -lxcb-shm -lxcb-util -lxcb-randr -static"

make DESTDIR="$1" PREFIX=/usr install

# Makefile doesnt install manpages
mkdir -p     "$1/usr/share/man/man1"
cp glazier.1 "$1/usr/share/man/man1"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
