#!/bin/sh -e

# vendor libwm, as its not needed elsewhere at all
(
cd libwm

make \
	CFLAGS="$CFLAGS -I/usr/include"
)

# change bordercolor
sed 's/deadca7/836421/' config.def.h > _
mv _ config.def.h

make
make DESTDIR="$1" PREFIX=/usr install

# Makefile doesnt install manpages
mkdir -p     "$1/usr/share/man/man1"
cp glazier.1 "$1/usr/share/man/man1"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
