#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static-pie"
export CFLAGS="$CFLAGS \
	-I/src/oakiss/out/pkg/jbig2dec/include \
	-fPIE \
    -DNDEBUG \
    -DFZ_ENABLE_JS=0 \
    -DFZ_ENABLE_JPX=0 \
    -DFZ_ENABLE_HTML=0 \
    -DFZ_ENABLE_EPUB=0 \
    -DNO_CJK \
    -DFZ_ENABLE_ICC=0 \
    -DNO_ICC \
    -DNOTO_SMALL \
    -DSHARE_JPEG"

for p in *.patch; do
    patch -p1 < "$p"
done

make \
    prefix="/usr" \
    build=release \
    HAVE_X11=yes \
    HAVE_CURL=no \
    HAVE_WAYLAND=no \
    HAVE_GLUT=no \
    USE_SYSTEM_OPENJPEG=no \
    USE_SYSTEM_LIBS=yes \
    shared=no \
    THIRD_LIBS="/usr/lib/*.a -lfreetype -lharfbuzz -lfontconfig -ljpeg -lz -lpng16 /src/oakiss/out/pkg/jbig2dec/libjbig2dec.a" \
    X11_LIBS="-lxcb -lX11 -lXau -lXext" \
    install-apps install-docs

mv -f "$1/usr/bin/mupdf-x11" "$1/usr/bin/mupdf"

# remove docs, but keep manpages
rm -rf "$1/usr/share/doc"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
