#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done
make LDFLAGS="$LDFLAGS -lXft -lXrender -lX11 -lpthread -lxcb -lXau -lfontconfig -lfreetype -lharfbuzz -pthread -lexpat -lm -static" \
	XINERAMALIBS='' \
	XINERAMAFLAGS='' \
	X11INC=/usr/include \
	X11LIB=/usr/lib
make DESTDIR="$1" PREFIX=/usr install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
