#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" PREFIX=/pkg install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
