#!/bin/sh -e

./configure \
    --prefix=/pkg \
    --enable-pcre2-16 \
    --enable-pcre2-32 \
    --enable-pcre2grep-libz \
    --enable-jit

make
make DESTDIR="$1" install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
