#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static -lxcb -lXau"

make
make DESTDIR="$1" PREFIX=/pkg install

# Remove docs
rm -rf "$1/pkg/share/doc"

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
