#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static -lxcb -lXau"

make
make DESTDIR="$1" PREFIX=/usr install

# Remove docs
rm -rf "$1/usr/share/doc"

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +
