#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 0001-remove-fribidi-dependency.patch

# Disable native language support, disable atk-bridge, don't compile schemas.
sed -e '/compile_schemas/s/true/false/' \
    -e '/ENABLE_NLS/s/1/0/' \
    -e "/subdir('po/d" \
    -e "/atk-bridge/d" \
    meson.build > _
mv -f _ meson.build

# Remove atk-bridge code.
sed '/<atk-bridge.h>/d;/atk_bridge_adaptor_init/d' \
    gtk/a11y/gtkaccessibility.c > _
mv -f _ gtk/a11y/gtkaccessibility.c

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Db_colorout=never \
	-Ddebug=false \
	-Doptimization=s \
	-Dx11_backend=true \
	-Dwayland_backend=false \
	-Dxinerama=yes \
	-Dprint_backends=file,lpr \
	-Dcolord=no \
	-Dintrospection=false \
	-Ddemos=false \
	-Dexamples=false \
	-Dtests=false \
	build

samu -C build
samu -C build install

# We don't compile with librsvg which leads to this utility solely causing
# compiler errors for some packages. It has no use at all.
rm -f "$1/usr/bin/gtk-encode-symbolic-svg"
