#!/bin/sh -e

export PKG_CONFIG_PATH=/usr/lib/pkgconfig

for p in *.patch; do
	patch -p1 < "$p"
done

./configure \
    prefix=/usr

make NCURSES_LIBS="-lcurses -lterminfo"
make DESTDIR="$1"  install

# Compress manpages
find "$1/usr/share/man" -type f -exec gzip -n -9 {} +

rm -rf "$1/usr/share/doc"
