#!/bin/sh -e

# shellcheck disable=SC2016

# dont use xinerama
sed -e 's/\${XINERAMALIBS}//' \
	-e 's/\${XINERAMAFLAGS}//' \
	config.mk > _
mv -f _ config.mk

make
make DESTDIR="$1" PREFIX=/usr install

# Compress manpages
find "$1/usr/share/man" -type f | xargs gzip -n -9
