#!/bin/sh -e

export CFLAGS="$CFLAGS -I/pkg/include"
export LDFLAGS="$LDFLAGS -L/pkg/lib -Wl,-rpath=/pkg/lib"

# shellcheck disable=SC2016

# dont use xinerama
sed -e 's/\${XINERAMALIBS}//' \
	-e 's/\${XINERAMAFLAGS}//' \
	config.mk > _
mv -f _ config.mk

make
make DESTDIR="$1" PREFIX=/pkg install

# Compress manpages
find "$1/pkg/share/man" -type f | xargs gzip -n -9
