#!/bin/sh -e

TMPDIR="$1/tmp"

./configure \
    --host=x86_64-linux-musl \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --without-xmlto \
    --disable-specs \
    --disable-shared

make
make DESTDIR="$1" install

# Some X11 packages install to /usr/share.
! [ -d "$1/usr/share/pkgconfig" ] || {
    mkdir -p "$1/usr/lib"
    mv -f "$1/usr/share/pkgconfig" "$1/usr/lib"
}

# We need to keep this around.
! [ -d "$1/usr/share/aclocal" ] || {
    mkdir -p "$TMPDIR"
    mv -f "$1/usr/share/aclocal" "$TMPDIR"
}

# Restore kept directories.
! [ -d "$TMPDIR" ] || {
    mv -f "$TMPDIR/"* "$1/usr/share"
    rm -rf "$TMPDIR"
}

# Remove docs
rm -rf "$1/usr/share/doc"
