#!/bin/sh -e

export DESTDIR="$1"

TMPDIR="$1/tmp"

./configure \
    --host=x86_64-linux-musl \
    --prefix=/ \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --without-xmlto \
    --disable-specs \
    --disable-shared

make
make install

# Some X11 packages install to /share.
! [ -d "$1/share/pkgconfig" ] || {
    mkdir -p "$1/lib"
    mv -f "$1/share/pkgconfig" "$1/lib"
}

# We need to keep this around.
! [ -d "$1/share/aclocal" ] || {
    mkdir -p "$TMPDIR"
    mv -f "$1/share/aclocal" "$TMPDIR"
}

# Restore kept directories.
! [ -d "$TMPDIR" ] || {
    mv -f "$TMPDIR/"* "$1/share"
    rm -rf "$TMPDIR"
}

# Remove docs
rm -rf "$1/share/doc"
